name: .NET Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test with coverage
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults
          reportgenerator -reports:./TestResults/**/coverage.cobertura.xml -targetdir:./TestResults/coverage-report -reporttypes:TextSummary

      - name: Check coverage threshold
        run: |
          COVERAGE=$(grep -o 'Line coverage.*[0-9]\+\.[0-9]\+%' ./TestResults/coverage-report/Summary.txt | grep -o '[0-9]\+\.[0-9]\+')
          echo "Line coverage: $COVERAGE%"
          COVERAGE_INT=${COVERAGE%.*}
          if [ "$COVERAGE_INT" -lt 90 ]; then
            echo "Test coverage is below 90% ($COVERAGE%)" >&2
            exit 1
          fi
        shell: bash

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./TestResults/coverage-report
