name: .NET Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore DisbordAIBot/DisbordAIBot.sln

      - name: Build
        run: dotnet build DisbordAIBot/DisbordAIBot.sln --no-restore --configuration Release

      - name: Test with coverage
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet test DisbordAIBot/DisbordAIBot.sln --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults
          reportgenerator -reports:./TestResults/**/coverage.cobertura.xml -targetdir:./TestResults/coverage-report -reporttypes:TextSummary

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./TestResults/coverage-report
